#!/usr/bin/env bash
# =============================================================================
# deploy.sh — Run this on the EC2 instance to deploy / update the app.
#
# Usage (first time):
#   scp -r . ec2-user@<EC2_IP>:/opt/app
#   ssh ec2-user@<EC2_IP> "bash /opt/app/scripts/deploy.sh"
#
# Usage (update):
#   ssh ec2-user@<EC2_IP> "cd /opt/app && git pull && bash scripts/deploy.sh"
# =============================================================================
set -euo pipefail

APP_DIR="/opt/app"
REGION="${AWS_REGION:-us-east-1}"
SECRET_NAME="ai-learning/db-credentials"

echo "==> [1/6] Fetching DB credentials from Secrets Manager..."
SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "$SECRET_NAME" \
  --region "$REGION" \
  --query SecretString \
  --output text)

DB_USER=$(echo "$SECRET_JSON"     | python3 -c "import sys,json; print(json.load(sys.stdin)['username'])")
DB_PASSWORD=$(echo "$SECRET_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['password'])")

# RDS endpoint is passed as env var from CDK output or set manually
DB_HOST="${DB_HOST:-}"
DB_NAME="${DB_NAME:-ailearning}"
DB_PORT="${DB_PORT:-5432}"

echo "==> [2/6] Writing .env file..."
USE_ANTHROPIC_DIRECT="${USE_ANTHROPIC_DIRECT:-false}"
BEDROCK_MODEL_ID_VALUE="${BEDROCK_MODEL_ID:-amazon.nova-lite-v1:0}"

cat > "$APP_DIR/backend/.env" << EOF
# Auto-generated by deploy.sh — do not edit manually
PORT=4000
AWS_REGION=${REGION}
S3_BUCKET_NAME=${S3_BUCKET_NAME}
BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID_VALUE}
USE_ANTHROPIC_DIRECT=${USE_ANTHROPIC_DIRECT}
PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-}

# Optional Bedrock/Anthropic model fallbacks
BEDROCK_FALLBACK_MODEL_IDS=${BEDROCK_FALLBACK_MODEL_IDS:-}
ANTHROPIC_MODEL=${ANTHROPIC_MODEL:-claude-sonnet-4-6}
ANTHROPIC_FALLBACK_MODELS=${ANTHROPIC_FALLBACK_MODELS:-}

# Optional media providers
YOUTUBE_API_KEY=${YOUTUBE_API_KEY:-}
VIMEO_ACCESS_TOKEN=${VIMEO_ACCESS_TOKEN:-}
STOCK_IMAGE_API_KEY=${STOCK_IMAGE_API_KEY:-}
AI_IMAGE_API_URL=${AI_IMAGE_API_URL:-}
AI_IMAGE_API_KEY=${AI_IMAGE_API_KEY:-}

# RDS
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
EOF

if [ "$USE_ANTHROPIC_DIRECT" = "true" ]; then
  if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
    echo "❌ USE_ANTHROPIC_DIRECT=true but ANTHROPIC_API_KEY is missing"
    exit 1
  fi
  echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" >> "$APP_DIR/backend/.env"
fi

echo "==> [3/6] Installing backend dependencies..."
cd "$APP_DIR/backend"
npm install --omit=dev

echo "==> [4/6] Building frontend..."
cd "$APP_DIR/frontend"
npm install
npm run build

echo "==> [5/6] Starting / restarting backend with PM2..."
cd "$APP_DIR/backend"
pm2 describe ai-learning-backend > /dev/null 2>&1 \
  && pm2 restart ai-learning-backend \
  || pm2 start index.js --name ai-learning-backend --update-env

pm2 save
CURRENT_USER=$(whoami)
pm2 startup systemd -u "$CURRENT_USER" --hp "/home/$CURRENT_USER" | tail -1 | bash || true

echo "==> [6/6] Reloading nginx..."
sudo nginx -t && sudo systemctl reload nginx

echo ""
echo "✅  Deploy complete!"
echo "    App is live at: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)"
